{"name": "Проверка вывода ошибки при авторизации курьера без логина", "status": "passed", "steps": [{"name": "Отправляем POST запрос на ручку /api/v1/courier/login", "status": "passed", "parameters": [{"name": "payloads", "value": "{'login': None, 'password': '123141'}"}], "start": 1733208042928, "stop": 1733208043233}, {"name": "Проверяем статус код", "status": "passed", "parameters": [{"name": "code", "value": "400"}], "start": 1733208043234, "stop": 1733208043234}, {"name": "Проверяем сообщение об ошибке Недостаточно данных для входа", "status": "passed", "steps": [{"name": "Получаем сообщение об ошибке", "status": "passed", "start": 1733208043234, "stop": 1733208043234}], "start": 1733208043234, "stop": 1733208043234}], "attachments": [{"name": "stdout", "source": "a276d1c2-5175-4402-83f8-56d9d357f367-attachment.txt", "type": "text/plain"}], "start": 1733208042928, "stop": 1733208043235, "uuid": "285e8dd2-fd1e-4c8e-9bac-c756b7a5c2ce", "historyId": "c9470b301924f17755f670a4b6d846f5", "testCaseId": "c9470b301924f17755f670a4b6d846f5", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_validation_error_on_empty_required_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-40MQLH4"}, {"name": "thread", "value": "6356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}